### ISSUE TITLE
Add Est Read time

### ISSUE THREAD

**Issue by clburlison** [clburlison/clburlison.github.io#39]
https://github.com/MiteshShah/miteshshah.github.io

https://miteshshah.github.io/guide/guest-post-guidelines/

**Comment by MiteshShah** [comment]
@clburlison https://github.com/MiteshShah/miteshshah.github.io/commit/c98c0de896d2a41baf8afc37a909eb312ac4c6e0

**Comment by clburlison** [comment]
Thank you very much.
